apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: microservices
  labels:
    app: catalog
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
      tier: backend
  template:
    metadata:
      labels:
        app: catalog
        tier: backend
    spec:
      containers:
        - name: catalog
          image: christiantagne/catalog:1.0.0
          env:
            - name: CSE_REGISTRY_ADDR
              value: http://servicecenter:30100
