apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicecenter
  namespace: microservices
  labels:
    app: servicecenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicecenter
  template:
    metadata:
      labels:
        app: servicecenter
    spec:
      containers:
        - name: servicecenter
          image: servicecomb/service-center:1.0.0
          ports:
            - containerPort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: servicecenter
  namespace: microservices
spec:
  selector:
    app: servicecenter
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: microservices
  labels:
    app: catalog
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
      tier: backend
  template:
    metadata:
      labels:
        app: catalog
        tier: backend
    spec:
      containers:
        - name: catalog
          image: christiantagne/catalog:1.0.0
          env:
            - name: CSE_REGISTRY_ADDR
              value: http://servicecenter:30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: microservices
  labels:
    app: payment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      tier: backend
  template:
    metadata:
      labels:
        app: payment
        tier: backend
    spec:
      containers:
      - env:
        - name: SC_HOST
          value: servicecenter
        image: christiantagne/payment:1.0.0
        name: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: christiantagne/frontend:1.0.0
        env:
        - name: http_proxy
          value: 127.0.0.1:30101
      - name: mesherfrontend
        image: thanda/mesher:osi
        env:
        - name: CSE_REGISTRY_ADDR
          value : http://servicecenter:30100
        - name: SERVICE_NAME
          value: frontend
        - name: VERSION
          value: 0.0.1
        - name: APP_ID
          value: OSIConference
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: mesherfrontend
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
