apiVersion: v1
kind: Service
metadata:
  name: servicecenter
  namespace: microservices
spec:
  selector:
    app: servicecenter
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
