apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: {{ .Release.Namespace }}
data:
  WORDPRESS_DB_HOST: "mysql.{{ .Release.Namespace }}.svc.cluster.local"
  WORDPRESS_DB_NAME: "{{ .Values.wordpress.env.WORDPRESS_DB_NAME }}"
