apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard