apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
  
type: Opaque
data:
  #This is base64 encoded --the real password is password
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # "password" encodé en base64
