apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:5-php7.1-apache
        volumeMounts:
          - name: wordpress-data
            mountPath: /var/www
          # - name: apache-config
          #   mountPath: /etc/apache2/sites-available/000-default.conf
          #   subPath: apache.conf
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_NAME
        ports:
        - containerPort: 80
          name: wordpress
      
      - name: mysql-client
        image: debian:latest
        command: ["sh", "-c", "apt update && apt install -y default-mysql-client && tail -f /dev/null"]

      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-volume
        # - name: apache-config
        #   configMap:
        #     name: apache-config
        #     items:
        #       - key: apache.conf
        #         path: apache.conf
