apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:  # ✅ Ajout du label
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    ports:
      - containerPort: 3306
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-data
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
  volumes:
  - name: mysql-data
    hostPath:
      path: /data-volume
      type: DirectoryOrCreate
