apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: simple-webapp-color-blue
  namespace: production
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: blue
    image: mmumshad/simple-webapp-color
    name: simple-webapp-color-blue
    ports:
    - containerPort: 8080
