apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-nodeport-web
  name: service-nodeport-web
  namespace: production
spec:
  ports:
  - name: 8080-8080
    nodePort: 30009
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
  type: NodePort
